org: millsp
app: prisma-serverless-webpack
service: prisma-serverless-webpack

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
